syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.some.grpc.inventory";

service InventoryService {
  rpc checkAvailability (ProductRequestDto) returns (ProductResponseDto);
}

message ProductRequestDto {
  string order_id = 1;
  map<string, int64> order_items = 2;
}

message ProductResponseDto {
  repeated OrderItemDto items = 1;
}

message OrderItemDto {
  string id = 1;
  string product_id = 2;
  string order_id = 3;
  string product_name = 4;
  int64 price_pennies = 5;
  int64 sale_pennies = 6;
  int64 total_price = 7;
  bool isAvailable = 8;
}